### ISSUE TITLE
Missing Documentation Issue Template in Repository

### ISSUE THREAD

**Issue by Nishitbaria** [vermaanurag1532/WHILE_APP#23]
**I want to add** 
`Documentation Template: ` This template facilitates the creation of comprehensive documentation by providing a structured format, including sections for an introduction, usage instructions, examples, and other relevant details.

**Comment by vermaanurag1532** [comment]
ok you can start your work

**Comment by Nishitbaria** [comment]
Someone has already Created so I am closing Issue
