### ISSUE TITLE
login page with authentication

### ISSUE THREAD

**Issue by vermaanurag1532** [vermaanurag1532/WHILE_APP#5]

**Comment by mridul45** [comment]
I would be happy to contribute to the project as I find my skills a good fit for the issue . As a GSSOC 23 member I humbly ask to allow me to contribute to the issue.

**Comment by Uttkarsh-raj** [comment]
I would like to contribute to this project and this issue can you assign this to me ....

**Comment by aspiringgarv** [comment]
Hi, I will be happy to tackle this issue, could you assign this to me?

**Comment by aspiringgarv** [comment]
I will be doing it with firebase authentication

**Comment by MihirCharan42** [comment]
Hi i would like to work on this issue as well, could you please assign this to me? I am GSSoC'2023 participant

**Comment by helloamj** [comment]
Hi @vermaanurag1532 , I wanna solve this issue as a gssoc 23 contributor, could you plz assign this to me

**Comment by vermaanurag1532** [comment]
@mridul45 I allot this issue to you but before that I want to discuss something with you so can you send me your number on my mail

**Comment by mridul45** [comment]
sure

**Comment by mridul45** [comment]
Can you provide me your mail id

**Comment by vermaanurag1532** [comment]
vermaanurag1532@gmail.com

**Comment by mridul45** [comment]
hi I have shared you the number
