### ISSUE TITLE
login and signup page

### ISSUE THREAD

**Issue by vermaanurag1532** [vermaanurag1532/WHILE_APP#6]

**Comment by aniket2125ec1117** [comment]
hello i am GSSOC 23 contributer and i want to work on this project because i am currently working on this .

**Comment by Saksham0205** [comment]
can you please assign me this issue under GSSoc 2023. I really want to work on this issue.

**Comment by Subhash23jan** [comment]
could you please assign it to me .I wanna develop this feature

**Comment by AnushkaKalra** [comment]
Hi, would be glad to get assigned to this issue. I'd like to contribute and work on it as a GSSoC'23 participant.

**Comment by sora-san45** [comment]
Heyy I can make beautiful login and sign up ui using flutter. Could you assign this to me

**Comment by ombhojane** [comment]
Hey, I recently made an signup/login page
Can you please assign this issue to me..
GSSOC 2023 :)
![image](https://github.com/vermaanurag1532/WHILE_APP/assets/82753658/fa47cfdb-cec3-4e1f-8e6a-2d104c313205)

**Comment by UMESH-042** [comment]
@vermaanurag1532  can you please assign this issue to me, I can create good looking UI for login and Signup, with their functionality using firebase by writing code using state management techniques like Flutter Bloc

**Comment by MUDITJAIN2** [comment]
I want to work on this as a part of GSSoC'23, I already have experience in Flutter UI, could you please assign it to me?

**Comment by indresh149** [comment]
@vermaanurag1532  can you assign me this issue?

**Comment by Apreksha** [comment]
Hey @vermaanurag1532, I'm a GSSoC'23 contributor. I can make a beautiful Login and Signup page with animations and transitions along with integration with Firebase and can also add OTP verification and Signin with Google. Could you please assign this task to me?

**Comment by Saksham0205** [comment]
please assign me this issue I had previously worked on sign in and sign-up page

**Comment by vermaanurag1532** [comment]
@ombhojane can you send me a message on my gmail vermaanurag1532@gmail.com

**Comment by avirupnandi1** [comment]
Hi...Assign me this issue....I can work on it...I have made some Login & signup pages earlier

**Comment by mridul45** [comment]
Hi the kindly assign the issue to me as I am already working on login with auth issue so it will be convenient to work on the signup also.

**Comment by prateekthakur272** [comment]
I can create login and sign up screen, and I can connect it through firebase authentication for login and signup

**Comment by prateekthakur272** [comment]
![Simulator Screenshot - iPhone 14 - 2023-05-26 at 11 27 36](https://github.com/vermaanurag1532/WHILE_APP/assets/67188426/f24cdc18-92e3-45b2-a480-27cf50fc0d78)

**Comment by mridul45** [comment]
I have already designed the UI and connected to firebase only some minor changes are there to make .
